# This workflow will publish a the Mapbox.NET package to NuGet 
# when a new tag is created on the main branch.

name: Publish Mapbox.NET to NuGet

on:
  push:
    branches: [ "main" ]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release Mapbox.NET
    - name: Publish
      run: dotnet nuget push Mapbox.NET/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json