name: PR workflow

on:
  pull_request: 
    branches: ["main"]

jobs: 
  build_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory coverage
      - uses: actions/upload-artifact@v4
        with:
          name: Mapbox.NET_coverage
          path: coverage/*/coverage.cobertura.xml
        
  coverage:
    needs: build_test
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Mapbox.NET_coverage
      - name: Display structure of downloaded files
        run: ls -R
      - name: Generate Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "**/coverage.cobertura.xml"
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md